import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import clsx from 'clsx';
import { Bars3Icon } from '@heroicons/react/24/solid';
import styles from 'styles/Home.module.css';
import { GRAPICS_MAP, FRENS_MAP } from 'helpers/constants';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Happygods.eth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="2xl:container mx-auto">
        <section id="home" className={styles.home}>
          <div className="flex items-center h-screen relative">
            <div className="ml-auto mr-4 md:mr-12 xl:mr-24 mb-24 text-end font-semibold">
              <h1 className="text-4xl md:text-5xl xl:text-6xl mb-2 md:mb-4 xl:mb-6">
                happygods.eth
              </h1>
              <p className="text-lg md:text-xl xl:text-2xl">
                A Nacho Frades collection all about happiness.
              </p>
            </div>
          </div>
        </section>

        <section id="about" className="md:mt-4 px-4 md:px-12 xl:px-24 mb-10">
          <div className="text-md md:text-lg xl:text-2xl font-semibold text-end">
            <p className="mb-6">
              Happygods is a collection of 128 hand made paintings about:
              <br /> happiness, luck, serenity, intelligence, love, money and
              wisdom.
            </p>
            <p className="mb-6">
              It&lsquo;s designed to be interesting and play with the
              attributes.
              <br /> All are different even having the same attributes, in
              example &ldquo;money&rdquo; and &ldquo;luck&rdquo;.
            </p>
            <p className="mb-4">
              Attributes are features each happygod has, there are:
            </p>
            <p className="mb-4">
              64 happygods with 2 attributes, 32 with 3 attributes,
              <br /> 16 with 4 attributes, 9 with 5 attributes, 6 with 6
              attributes
              <br /> and only one with the seven attributes,
              <br /> Each has it&lsquo;s own name and drawing and colors.
            </p>
            <p className="mb-6">
              64 happygods with 2 Attributes
              <br /> 32 happygods with 3 Attributes
              <br /> 16 happygods with 4 Attributes
              <br /> 9 happygods with 5 Attributes
              <br /> 6 happygods with 6 Attributes
              <br /> 1 happygods with 7 Attributes
            </p>
          </div>
        </section>

        <section id="graphics" className="px-4 md:px-12 xl:px-24 mb-10">
          <p className="text-md md:text-lg xl:text-2xl font-semibold text-end mb-10">
            Attributes are represented as a graphical feature:
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mx-auto max-w-fit">
            {GRAPICS_MAP.map(({ title, image }) => (
              <div key={title} className="flex items-center">
                <div className="flex mr-4">
                  <Image
                    src={
                      image ?? 'https://dummyimage.com/50x50/dddddd/000000.png'
                    }
                    alt={title}
                    width="50"
                    height="50"
                  />
                </div>
                <p className="uppercase text-md md:text-lg xl:text-2xl font-semibold">
                  {title}
                </p>
              </div>
            ))}
          </div>
        </section>

        <section
          id="epicon"
          className={clsx(styles.epicon, 'px-4 md:px-12 xl:px-24 mb-10')}
        >
          <div className="flex items-center justify-center h-96 relative">
            <p className="text-md md:text-lg xl:text-2xl font-semibold text-end">
              happygod 074, &ldquo;EPICON&rdquo; has the attributes:
              <br />
              WISDOM, MONEY, LUCK, that&lsquo;s it&lsquo;s a happygod with 3
              attributes.
            </p>
          </div>
        </section>

        <section id="frens" className="px-4 md:px-12 xl:px-24 mb-10">
          <div className="flex flex-col md:flex-row justify-center mx-auto max-w-fit">
            <p className="mb-2 text-end block md:hidden font-semibold">
              The 128 Frens:
            </p>
            <p
              className={clsx(
                styles.frensLabel,
                'mr-2 text-end hidden md:block font-semibold',
              )}
            >
              The 128 Frens:
            </p>
            <div className="grid grid-cols-4 md:grid-cols-11 gap-4 min-w-fit mx-auto">
              {FRENS_MAP.map(({ title, image }) => (
                <div key={title} className="flex flex-col w-14">
                  <Image
                    src={
                      image ?? 'https://dummyimage.com/50x50/dddddd/000000.png'
                    }
                    alt={title}
                    width="50"
                    height="50"
                  />
                  <p className="text-center font-semibold">{title}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section id="faq" className="px-4 md:px-12 xl:px-24 mb-10">
          <p className="font-semibold">HOW TO BUY? Easy!</p>
        </section>
      </main>
    </div>
  );
};

export default Home;
